spring:
  datasource:
    url: jdbc:postgresql://${FEIRASP_DATASOURCE_HOST:localhost}:5432/postgres?currentSchema=feira_app
    username: ${FEIRASP_DATASOURCE_USERNAME:feirasp_user}
    password: ${FEIRASP_DATASOURCE_PASSWORD:feirasp_pass}
  flyway:
    url: jdbc:postgresql://${FLYWAY_DATASOURCE_HOST:localhost}:5432/postgres
    user: ${FLYWAY_DATABASE_USER:postgres}
    password: ${FLYWAY_DATABASE_PASSWORD:postgres}
springdoc:
  api-docs:
    path: /api-docs